# Generated by Django 5.0.3 on 2024-03-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='carro',
            new_name='modelo',
        ),
    ]
