# Generated by Django 5.0.3 on 2024-03-28 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_rename_carro_carro_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('protocolo', models.CharField(max_length=20)),
                ('data_inicio', models.DateField(auto_now_add=True, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('criado', 'Serviço criado'), ('orcamento', 'Serviço em fase de orçamento'), ('aprovacao', 'Serviço aguardando aprovação do orçamento pelo cliente'), ('iniciado', 'Serviço iniciado'), ('aguardando', 'Serviço aguardando outros fatores para continuidade'), ('validacao', 'Serviço em validação pelo cliente'), ('finalizado', 'Serviço finalizado')], default='criado', max_length=50)),
                ('flag_finalizado', models.BooleanField(default=False)),
                ('categoria', models.ManyToManyField(to='servicos.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
        ),
    ]
