# Generated by Django 5.0.3 on 2024-03-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servico',
            name='protocolo',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
